/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetEthTokenAppraisalRequest { 
    /**
     * The contract address of the token collection.
     */
    collection_address: string;
    /**
     * The id(s) for the token(s).
     */
    token_id: Array<string>;
    /**
     * The currency to report results in
     */
    rept_curr?: GetEthTokenAppraisalRequest.ReptCurrEnum;
    /**
     * The interval at which to calculate intermediate results and forecasts.
     */
    frequency?: string;
    /**
     * The forecast horizon (i.e. the number of periods to forecast out). Defaults to zero which only returns nowcasts.
     */
    horizon?: number;
    /**
     * The significance level for the liquidation estimate, e.g. 0.05 for 95% confidence
     */
    alpha?: number;
    /**
     * Exclude suspected wash transactions?
     */
    exclude_wash?: boolean;
}
export namespace GetEthTokenAppraisalRequest {
    export type ReptCurrEnum = 'eth' | 'usd';
    export const ReptCurrEnum = {
        Eth: 'eth' as ReptCurrEnum,
        Usd: 'usd' as ReptCurrEnum
    };
}


