/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetEthCollectionSummaryRequest { 
    /**
     * The contract address of the collection.
     */
    collection_address: string;
    /**
     * An attribute of the NFT.
     */
    group_by?: string;
    /**
     * The start date to pull data for calculations
     */
    start_date?: string;
    /**
     * The end date to pull data for calculations
     */
    end_date?: string;
    /**
     * The currency to report results in
     */
    rept_curr?: GetEthCollectionSummaryRequest.ReptCurrEnum;
    /**
     * Exclude suspected wash transactions?
     */
    exclude_wash?: boolean;
}
export namespace GetEthCollectionSummaryRequest {
    export type ReptCurrEnum = 'eth' | 'usd';
    export const ReptCurrEnum = {
        Eth: 'eth' as ReptCurrEnum,
        Usd: 'usd' as ReptCurrEnum
    };
}


