/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetEthCollectionListingsOHLCRequest { 
    /**
     * The Ethereum contract address to identify the collection.
     */
    collection_address: string;
    /**
     * The interval at which to return OHLC, e.g. `1D` for daily, `1M` for monthly etc.
     */
    frequency?: string;
    /**
     * The currency to report results in
     */
    rept_curr?: GetEthCollectionListingsOHLCRequest.ReptCurrEnum;
    /**
     * The ISO 8601 date/datetime of the oldest listing to pull for calculations
     */
    listing_start_date?: string;
    /**
     * The ISO 8601 date/datetime of the most recent listing to pull for calculations
     */
    listing_end_date?: string;
    /**
     * The ISO 8601 start date/datetime to return results for
     */
    report_start_date?: string;
    /**
     * The ISO 8601 end date/datetime to return results for
     */
    report_end_date?: string;
}
export namespace GetEthCollectionListingsOHLCRequest {
    export type ReptCurrEnum = 'eth' | 'usd';
    export const ReptCurrEnum = {
        Eth: 'eth' as ReptCurrEnum,
        Usd: 'usd' as ReptCurrEnum
    };
}


