/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetEthHistoricalEventsRequest { 
    /**
     * The contract address of a collection.
     */
    collection_address: string;
    /**
     * The id for the token.
     */
    token_id?: string;
    /**
     * The pagination cursor.
     */
    page?: number;
    /**
     * The number of records returned per page.
     */
    page_size?: GetEthHistoricalEventsRequest.PageSizeEnum;
    /**
     * Only return events occuring after this day [YYYY-MM-DD]
     */
    event_date?: string;
    /**
     * The type of event: list, transfer, offer, mint, sale, cancel_list or cancel_offer
     */
    event_type?: GetEthHistoricalEventsRequest.EventTypeEnum;
}
export namespace GetEthHistoricalEventsRequest {
    export type PageSizeEnum = 50 | 100 | 500 | 1000;
    export const PageSizeEnum = {
        NUMBER_50: 50 as PageSizeEnum,
        NUMBER_100: 100 as PageSizeEnum,
        NUMBER_500: 500 as PageSizeEnum,
        NUMBER_1000: 1000 as PageSizeEnum
    };
    export type EventTypeEnum = 'list' | 'transfer' | 'offer' | 'mint' | 'sale' | 'cancel_list' | 'cancel_offer';
    export const EventTypeEnum = {
        List: 'list' as EventTypeEnum,
        Transfer: 'transfer' as EventTypeEnum,
        Offer: 'offer' as EventTypeEnum,
        Mint: 'mint' as EventTypeEnum,
        Sale: 'sale' as EventTypeEnum,
        CancelList: 'cancel_list' as EventTypeEnum,
        CancelOffer: 'cancel_offer' as EventTypeEnum
    };
}


