/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * JSON containing options for the ARCH family model.
 */
export interface GetEthCollectionForecastsRequestArchParams { 
    /**
     * Estimator for the location model of the time series, e.g: `Zero`, `Constant`, `ARX`, ... . 
     */
    mean?: string;
    /**
     * Number of time time period lags considered. Note that the time period is set by the `frequency` parameter, so a value of 2 will assume 2-day lags if `frequency==\'1D\'`.
     */
    lags?: number;
    /**
     * Estimator used for the volatility process of the time series, e.g: `Constant`, `ARCH`, `GARCH`, ... 
     */
    vol?: string;
    /**
     * Order of the symmetric innovation(s).
     */
    p?: number;
    /**
     * Return distribution assumed.
     */
    dist?: GetEthCollectionForecastsRequestArchParams.DistEnum;
}
export namespace GetEthCollectionForecastsRequestArchParams {
    export type DistEnum = 'norm' | 't';
    export const DistEnum = {
        Norm: 'norm' as DistEnum,
        T: 't' as DistEnum
    };
}


