/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetEthCollectionsRequest { 
    /**
     * The pagination cursor.
     */
    page?: number;
    /**
     * The number of records returned per page.
     */
    page_size?: GetEthCollectionsRequest.PageSizeEnum;
    /**
     * The name of the collection searched.
     */
    collection_name?: string;
    /**
     * Only return collections that have traded.
     */
    traded?: boolean;
    /**
     * Only return collections recorded after this day [YYYY-MM-DD]
     */
    created_after?: string;
    /**
     * The value to sort by. Defaults to created_at
     */
    sort_by?: GetEthCollectionsRequest.SortByEnum;
}
export namespace GetEthCollectionsRequest {
    export type PageSizeEnum = 50 | 100 | 500 | 1000;
    export const PageSizeEnum = {
        NUMBER_50: 50 as PageSizeEnum,
        NUMBER_100: 100 as PageSizeEnum,
        NUMBER_500: 500 as PageSizeEnum,
        NUMBER_1000: 1000 as PageSizeEnum
    };
    export type SortByEnum = 'created_at' | 'collection_name';
    export const SortByEnum = {
        CreatedAt: 'created_at' as SortByEnum,
        CollectionName: 'collection_name' as SortByEnum
    };
}


