/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetEthMarketplaceDataRequest { 
    /**
     * Array of collection addresses
     */
    collection_address: Array<string>;
    /**
     * Array of sub collections (e.g. Art Blocks)
     */
    sub_collection_tags?: Array<string>;
    /**
     * Return normalized data across marketplaces
     */
    normalized?: boolean;
}

