/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetPolTokenSummaryRequest { 
    /**
     * The contract address of the token collection.
     */
    collection_address: string;
    /**
     * The id for the token.
     */
    token_id: Array<string>;
    /**
     * The start date to pull data for calculations
     */
    start_date?: string;
    /**
     * The end date to pull data for calculations
     */
    end_date?: string;
    /**
     * The currency to report results in
     */
    rept_curr?: GetPolTokenSummaryRequest.ReptCurrEnum;
    /**
     * Exclude suspected wash transactions?
     */
    exclude_wash?: boolean;
}
export namespace GetPolTokenSummaryRequest {
    export type ReptCurrEnum = 'eth' | 'usd' | 'matic';
    export const ReptCurrEnum = {
        Eth: 'eth' as ReptCurrEnum,
        Usd: 'usd' as ReptCurrEnum,
        Matic: 'matic' as ReptCurrEnum
    };
}


