/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetPolTokenTransactionsRequest { 
    /**
     * The contract address the token belongs to.
     */
    collection_address: string;
    /**
     * The token id.
     */
    token_id: string;
    /**
     * The pagination cursor.
     */
    page?: number;
    /**
     * The number of records returned per page.
     */
    page_size?: GetPolTokenTransactionsRequest.PageSizeEnum;
    /**
     * The earliest block timestamp.
     */
    start_date?: string;
    /**
     * The oldest block number to return.
     */
    start_block_number?: number;
    /**
     * The latest block timestamp.
     */
    end_date?: string;
}
export namespace GetPolTokenTransactionsRequest {
    export type PageSizeEnum = 50 | 100 | 500 | 1000;
    export const PageSizeEnum = {
        NUMBER_50: 50 as PageSizeEnum,
        NUMBER_100: 100 as PageSizeEnum,
        NUMBER_500: 500 as PageSizeEnum,
        NUMBER_1000: 1000 as PageSizeEnum
    };
}


