/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetPolCollectionSalesOHLCRequest { 
    /**
     * The Polygon contract address to identify the collection.
     */
    collection_address: string;
    /**
     * The interval at which to return OHLC, e.g. `1D` for daily, `1M` for monthly etc.
     */
    frequency?: string;
    /**
     * An attribute of the NFT to group results by.
     */
    group_by?: string;
    /**
     * If \'true\', response dicts contain OHLCV
     */
    volume?: boolean;
    /**
     * If \'true\', append number of trades to OHLC(V)
     */
    n_trades?: boolean;
    /**
     * The currency to report results in
     */
    rept_curr?: GetPolCollectionSalesOHLCRequest.ReptCurrEnum;
    /**
     * The start date to pull data for calculations
     */
    start_date?: string;
    /**
     * The end date to pull data for calculations
     */
    end_date?: string;
    /**
     * Exclude suspected wash transactions?
     */
    exclude_wash?: boolean;
}
export namespace GetPolCollectionSalesOHLCRequest {
    export type ReptCurrEnum = 'eth' | 'usd' | 'matic';
    export const ReptCurrEnum = {
        Eth: 'eth' as ReptCurrEnum,
        Usd: 'usd' as ReptCurrEnum,
        Matic: 'matic' as ReptCurrEnum
    };
}


