/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetSolTokenAppraisalRequest { 
    /**
     * List of mint addresses of tokens to appraise
     */
    mint_address: Array<string>;
    /**
     * The currency to report results in
     */
    rept_curr?: GetSolTokenAppraisalRequest.ReptCurrEnum;
    /**
     * The interval at which to calculate intermediate results and forecasts.
     */
    frequency?: string;
    /**
     * The forecast horizon (i.e. the number of periods to forecast out). Defaults to zero which only returns nowcasts.
     */
    horizon?: number;
    /**
     * The significance level for the liquidation estimate, e.g. 0.05 for 95% confidence
     */
    alpha?: number;
    /**
     * Exclude suspected wash transactions?
     */
    exclude_wash?: boolean;
}
export namespace GetSolTokenAppraisalRequest {
    export type ReptCurrEnum = 'sol' | 'usd';
    export const ReptCurrEnum = {
        Sol: 'sol' as ReptCurrEnum,
        Usd: 'usd' as ReptCurrEnum
    };
}


