/**
 * Gallop API
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetSolDefaultCollectionRiskRequest { 
    /**
     * The Gallop tag to identify the collection.
     */
    collection_tag: string;
    /**
     * The holding period to evaluate risk for, e.g. \'12M\'
     */
    holding_period: string;
    /**
     * The amount of tokens in your portfolio
     */
    amount?: number;
    /**
     * The currency to report results in
     */
    rept_curr?: GetSolDefaultCollectionRiskRequest.ReptCurrEnum;
    /**
     * If true, report drawdown volatility (based on negative returns only).
     */
    drawdown?: boolean;
}
export namespace GetSolDefaultCollectionRiskRequest {
    export type ReptCurrEnum = 'sol' | 'usd';
    export const ReptCurrEnum = {
        Sol: 'sol' as ReptCurrEnum,
        Usd: 'usd' as ReptCurrEnum
    };
}


